import getMuiTheme from 'material-ui/styles/getMuiTheme';
import {
  appBarBackground,
  appBarText,
  navigationItemIcon,
  flatButtonPrimaryText,
  flatButtonSecondaryText,
  raisedButtonPrimaryText,
  raisedButtonPrimaryBackground,
  raisedButtonDefaultText,
  raisedButtonDefaultBackground,
  raisedButtonSecondaryText,
  raisedButtonSecondaryBackground,
  raisedButtonPrimaryDisabledText,
  raisedButtonPrimaryDisabledBackground,
  radioButtonBorder,
  radioButtonChecked,
  checkboxLabel,
  checkboxBorder,
  checkboxChecked,
  textFieldText,
  textFieldHint,
  textFieldFloatingLabel,
  textFieldError,
  textFieldFocus,
  textFieldBackground,
  textFieldBorder,
} from './colors.css';

export default getMuiTheme({
  fontFamily: 'MuseoSansRounded',
  appBar: {
    color: appBarBackground,
    textColor: appBarText,
  },
  menuItem: {
    dataHeight: 32,
    height: 48,
    rightIconDesktopFill: navigationItemIcon,
  },
  flatButton: {
    primaryTextColor: flatButtonPrimaryText,
    fontSize: '1.4rem',
    fontWeight: '500',
    secondaryTextColor: flatButtonSecondaryText,
  },
  raisedButton: {
    color: raisedButtonDefaultBackground,
    textColor: raisedButtonDefaultText,
    primaryColor: raisedButtonPrimaryBackground,
    primaryTextColor: raisedButtonPrimaryText,
    secondaryColor: raisedButtonSecondaryBackground,
    secondaryTextColor: raisedButtonSecondaryText,
    disabledColor: raisedButtonPrimaryDisabledBackground,
    disabledTextColor: raisedButtonPrimaryDisabledText,
    fontSize: '1.4rem',
    fontWeight: '500',
  },
  radioButton: {
    borderColor: radioButtonBorder,
    checkedColor: radioButtonChecked,
    labelColor: checkboxLabel,
  },
  checkbox: {
    boxColor: checkboxBorder,
    checkedColor: checkboxChecked,
    labelColor: checkboxLabel,
  },
  textField: {
    textColor: textFieldText,
    hintColor: textFieldHint,
    floatingLabelColor: textFieldFloatingLabel,
    errorColor: textFieldError,
    focusColor: textFieldFocus,
    backgroundColor: textFieldBackground,
    borderColor: textFieldBorder,
  },
});
